2025-07-05 20:10:30,650 INFO    MainThread:22904 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-07-05 20:10:30,650 INFO    MainThread:22904 [wandb_setup.py:_flush():70] Configure stats pid to 22904
2025-07-05 20:10:30,650 INFO    MainThread:22904 [wandb_setup.py:_flush():70] Loading settings from C:\Users\Lenovo Yoga\.config\wandb\settings
2025-07-05 20:10:30,650 INFO    MainThread:22904 [wandb_setup.py:_flush():70] Loading settings from C:\Users\Lenovo Yoga\Desktop\MycoAI\wandb\settings
2025-07-05 20:10:30,650 INFO    MainThread:22904 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-07-05 20:10:30,650 INFO    MainThread:22904 [wandb_init.py:setup_run_log_directory():724] Logging user logs to C:\Users\Lenovo Yoga\Desktop\MycoAI\wandb\run-20250705_201030-ibywueyv\logs\debug.log
2025-07-05 20:10:30,651 INFO    MainThread:22904 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to C:\Users\Lenovo Yoga\Desktop\MycoAI\wandb\run-20250705_201030-ibywueyv\logs\debug-internal.log
2025-07-05 20:10:30,651 INFO    MainThread:22904 [wandb_init.py:init():852] calling init triggers
2025-07-05 20:10:30,651 INFO    MainThread:22904 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'architecture': 'resnet50', 'epochs': 100, 'batch_size': 20, 'learning_rate': 0.0005, 'image_size': 224, 'optimizer': 'Adam', 'loss': 'CrossEntropyWeighted', '_wandb': {}}
2025-07-05 20:10:30,651 INFO    MainThread:22904 [wandb_init.py:init():893] starting backend
2025-07-05 20:10:30,651 INFO    MainThread:22904 [wandb_init.py:init():897] sending inform_init request
2025-07-05 20:10:30,690 INFO    MainThread:22904 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-07-05 20:10:30,690 INFO    MainThread:22904 [wandb_init.py:init():907] backend started and connected
2025-07-05 20:10:30,692 INFO    MainThread:22904 [wandb_init.py:init():1005] updated telemetry
2025-07-05 20:10:30,742 INFO    MainThread:22904 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-07-05 20:10:31,374 INFO    MainThread:22904 [wandb_init.py:init():1104] starting run threads in backend
2025-07-05 20:10:31,583 INFO    MainThread:22904 [wandb_run.py:_console_start():2573] atexit reg
2025-07-05 20:10:31,586 INFO    MainThread:22904 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-07-05 20:10:31,587 INFO    MainThread:22904 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-07-05 20:10:31,587 INFO    MainThread:22904 [wandb_run.py:_redirect():2513] Redirects installed.
2025-07-05 20:10:31,591 INFO    MainThread:22904 [wandb_init.py:init():1150] run started, returning control to user process
2025-07-05 20:11:43,537 WARNING MsgRouterThr:22904 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 208, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\router.py", line 56, in message_loop
    msg = self._read_message()
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-07-05 20:11:43,547 INFO    MsgRouterThr:22904 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
