2025-07-06 02:04:16,668 INFO    MainThread:20960 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-07-06 02:04:16,668 INFO    MainThread:20960 [wandb_setup.py:_flush():70] Configure stats pid to 20960
2025-07-06 02:04:16,668 INFO    MainThread:20960 [wandb_setup.py:_flush():70] Loading settings from C:\Users\Lenovo Yoga\.config\wandb\settings
2025-07-06 02:04:16,668 INFO    MainThread:20960 [wandb_setup.py:_flush():70] Loading settings from C:\Users\Lenovo Yoga\Desktop\MycoAI\wandb\settings
2025-07-06 02:04:16,668 INFO    MainThread:20960 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-07-06 02:04:16,669 INFO    MainThread:20960 [wandb_init.py:setup_run_log_directory():724] Logging user logs to C:\Users\Lenovo Yoga\Desktop\MycoAI\wandb\run-20250706_020416-4xpcq4f7\logs\debug.log
2025-07-06 02:04:16,669 INFO    MainThread:20960 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to C:\Users\Lenovo Yoga\Desktop\MycoAI\wandb\run-20250706_020416-4xpcq4f7\logs\debug-internal.log
2025-07-06 02:04:16,669 INFO    MainThread:20960 [wandb_init.py:init():852] calling init triggers
2025-07-06 02:04:16,669 INFO    MainThread:20960 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'architecture': 'resnet152', 'epochs': 100, 'batch_size': 16, 'learning_rate': 0.0005, 'image_size': 224, 'optimizer': 'Adam', 'loss': 'CrossEntropyWeighted', '_wandb': {}}
2025-07-06 02:04:16,669 INFO    MainThread:20960 [wandb_init.py:init():893] starting backend
2025-07-06 02:04:16,669 INFO    MainThread:20960 [wandb_init.py:init():897] sending inform_init request
2025-07-06 02:04:16,716 INFO    MainThread:20960 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-07-06 02:04:16,716 INFO    MainThread:20960 [wandb_init.py:init():907] backend started and connected
2025-07-06 02:04:16,717 INFO    MainThread:20960 [wandb_init.py:init():1005] updated telemetry
2025-07-06 02:04:16,763 INFO    MainThread:20960 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-07-06 02:04:17,373 INFO    MainThread:20960 [wandb_init.py:init():1104] starting run threads in backend
2025-07-06 02:04:17,655 INFO    MainThread:20960 [wandb_run.py:_console_start():2573] atexit reg
2025-07-06 02:04:17,658 INFO    MainThread:20960 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-07-06 02:04:17,658 INFO    MainThread:20960 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-07-06 02:04:17,658 INFO    MainThread:20960 [wandb_run.py:_redirect():2513] Redirects installed.
2025-07-06 02:04:17,663 INFO    MainThread:20960 [wandb_init.py:init():1150] run started, returning control to user process
2025-07-06 02:04:36,091 WARNING MsgRouterThr:20960 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 208, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\router.py", line 56, in message_loop
    msg = self._read_message()
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-07-06 02:04:36,098 INFO    MsgRouterThr:20960 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-07-06 02:04:36,162 ERROR   MainThread:20960 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
2025-07-06 02:04:36,303 ERROR   MainThread:20960 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
2025-07-06 02:04:36,465 ERROR   MainThread:20960 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
2025-07-06 02:04:36,673 ERROR   MainThread:20960 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
2025-07-06 02:04:36,819 ERROR   MainThread:20960 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
    ~~^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
    ~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
    ~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto
