2025-07-06 02:03:36,748 INFO    MainThread:9560 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-07-06 02:03:36,749 INFO    MainThread:9560 [wandb_setup.py:_flush():70] Configure stats pid to 9560
2025-07-06 02:03:36,749 INFO    MainThread:9560 [wandb_setup.py:_flush():70] Loading settings from C:\Users\Lenovo Yoga\.config\wandb\settings
2025-07-06 02:03:36,749 INFO    MainThread:9560 [wandb_setup.py:_flush():70] Loading settings from C:\Users\Lenovo Yoga\Desktop\MycoAI\wandb\settings
2025-07-06 02:03:36,749 INFO    MainThread:9560 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-07-06 02:03:36,749 INFO    MainThread:9560 [wandb_init.py:setup_run_log_directory():724] Logging user logs to C:\Users\Lenovo Yoga\Desktop\MycoAI\wandb\run-20250706_020336-4wti77m3\logs\debug.log
2025-07-06 02:03:36,750 INFO    MainThread:9560 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to C:\Users\Lenovo Yoga\Desktop\MycoAI\wandb\run-20250706_020336-4wti77m3\logs\debug-internal.log
2025-07-06 02:03:36,750 INFO    MainThread:9560 [wandb_init.py:init():852] calling init triggers
2025-07-06 02:03:36,750 INFO    MainThread:9560 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'architecture': 'mobilenet', 'epochs': 100, 'batch_size': 16, 'learning_rate': 0.0005, 'image_size': 224, 'optimizer': 'Adam', 'loss': 'CrossEntropyWeighted', '_wandb': {}}
2025-07-06 02:03:36,750 INFO    MainThread:9560 [wandb_init.py:init():893] starting backend
2025-07-06 02:03:36,750 INFO    MainThread:9560 [wandb_init.py:init():897] sending inform_init request
2025-07-06 02:03:36,798 INFO    MainThread:9560 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-07-06 02:03:36,798 INFO    MainThread:9560 [wandb_init.py:init():907] backend started and connected
2025-07-06 02:03:36,799 INFO    MainThread:9560 [wandb_init.py:init():1005] updated telemetry
2025-07-06 02:03:36,864 INFO    MainThread:9560 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-07-06 02:03:37,564 INFO    MainThread:9560 [wandb_init.py:init():1104] starting run threads in backend
2025-07-06 02:03:39,607 INFO    MainThread:9560 [wandb_run.py:_console_start():2573] atexit reg
2025-07-06 02:03:39,607 INFO    MainThread:9560 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-07-06 02:03:39,608 INFO    MainThread:9560 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-07-06 02:03:39,608 INFO    MainThread:9560 [wandb_run.py:_redirect():2513] Redirects installed.
2025-07-06 02:03:39,616 INFO    MainThread:9560 [wandb_init.py:init():1150] run started, returning control to user process
2025-07-06 02:03:54,712 WARNING MsgRouterThr:9560 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 208, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
ConnectionResetError: [WinError 10054] Se ha forzado la interrupción de una conexión existente por el host remoto

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\router.py", line 56, in message_loop
    msg = self._read_message()
  File "C:\Users\Lenovo Yoga\AppData\Local\Programs\Python\Python313\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-07-06 02:03:54,842 INFO    MsgRouterThr:9560 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
